### ISSUE TITLE
If IMG not found image file , will be crush

### ISSUE THREAD

**Issue by JokerCatz** [amardaxini/acts_as_flying_saucer#2]
First , sorry my pool English.

I love this plugin :) but I found some major bug in this plugin

like IMG tag can't found src image file(maybe 404) , all process will be stuck...same problem like backgound-image : url in CSS

can you help me to fix that? , this bug look like in the Java build...I can't fix that...

**Comment by amardaxini** [comment]
Hi,Use latest version of gem.
Flying saucer require actual url like http://xyz.com/images/abc.png. i
if you are using rails it is not required although can you try debug and
view HTML and then generate try to generate pdf.

On Thu, Jun 16, 2011 at 2:32 PM, JokerCatz <
reply@reply.github.com>wrote:

> First , sorry my pool English.
> 
> I love this plugin :) but I found some major bug in this plugin
> 
> like IMG tag can't found src image file(maybe 404) , all process will be
> stuck...same problem like backgound-image : url in CSS
> 
> can you help me to fix that? , this bug look like in the Java build...I
> can't fix that...
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/amardaxini/acts_as_flying_saucer/issues/2

## 

Thanks.
Amar Daxini

**Comment by JokerCatz** [comment]
:) thanx reply

yep I know it's need actual url , but the url is miss , the rails process will be stuck & client(browser) will always watting...

and another , can you add this in readme? my old issue report in another author of acts_as_flying_saucer
https://github.com/dagi3d/acts_as_flying_saucer/issues/3

**Comment by amardaxini** [comment]
Hi,
Can you add add top of HTML TAG
<?xml version='1.0' encoding='utf-8' ?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

If not added add above line if this is not work for let me know.

On Thu, Jun 16, 2011 at 3:39 PM, JokerCatz <
reply@reply.github.com>wrote:

> :) thanx reply
> 
> yep I know it's need actual url , but the url is miss , the rails process
> will be stuck & client(browser) will always watting...
> 
> and another , can you add this in readme? my old issue report in another
> author of acts_as_flying_saucer
> https://github.com/dagi3d/acts_as_flying_saucer/issues/3
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/amardaxini/acts_as_flying_saucer/issues/2#issuecomment-1379992

## 

Thanks.
Amar Daxini
